import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Heart, 
  ArrowLeft, 
  Download, 
  Calendar,
  Activity,
  AlertTriangle,
  TrendingUp,
  FileText
} from "lucide-react";
import { HealthChart } from "@/components/HealthChart";

const Reports = () => {
  const navigate = useNavigate();
  const [healthData, setHealthData] = useState<any[]>([]);
  const [symptomsData, setSymptomsData] = useState<any[]>([]);

  useEffect(() => {
    // Load stored data
    const health = JSON.parse(localStorage.getItem("healthData") || "[]");
    const symptoms = JSON.parse(localStorage.getItem("symptomsData") || "[]");
    setHealthData(health);
    setSymptomsData(symptoms);
  }, []);

  // Generate mock comprehensive report data
  const generateReport = () => {
    const report = {
      patientName: "John Doe",
      reportDate: new Date().toLocaleDateString(),
      period: "Last 30 Days",
      summary: {
        totalReadings: healthData.length + 15, // Adding mock historical data
        avgHeartRate: 72,
        avgBloodPressure: "120/80",
        avgBloodSugar: 95,
        symptomsReported: symptomsData.length + 3
      },
      riskAssessment: {
        diabetes: { risk: 25, trend: "stable" },
        heartDisease: { risk: 40, trend: "improving" },
        alzheimer: { risk: 15, trend: "stable" }
      },
      recommendations: [
        "Continue monitoring blood pressure daily",
        "Increase physical activity to 150 minutes per week",
        "Consider consulting with cardiologist about elevated heart disease risk",
        "Maintain current medication regimen"
      ]
    };
    return report;
  };

  const report = generateReport();

  const handleDownloadReport = () => {
    const reportText = `
EARLY DISEASE AI - HEALTH REPORT
================================

Patient: ${report.patientName}
Report Date: ${report.reportDate}
Period: ${report.period}

SUMMARY
-------
Total Health Readings: ${report.summary.totalReadings}
Average Heart Rate: ${report.summary.avgHeartRate} bpm
Average Blood Pressure: ${report.summary.avgBloodPressure} mmHg
Average Blood Sugar: ${report.summary.avgBloodSugar} mg/dL
Symptoms Reported: ${report.summary.symptomsReported}

RISK ASSESSMENT
---------------
Diabetes Risk: ${report.riskAssessment.diabetes.risk}% (${report.riskAssessment.diabetes.trend})
Heart Disease Risk: ${report.riskAssessment.heartDisease.risk}% (${report.riskAssessment.heartDisease.trend})
Alzheimer's Risk: ${report.riskAssessment.alzheimer.risk}% (${report.riskAssessment.alzheimer.trend})

RECOMMENDATIONS
---------------
${report.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

Generated by EarlyDiseaseAI Health Monitoring System
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `health-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => navigate("/dashboard")}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Dashboard
            </Button>
            <div className="flex items-center gap-2">
              <FileText className="h-6 w-6 text-primary" />
              <h1 className="text-xl font-semibold">Health Reports</h1>
            </div>
          </div>
          <Button onClick={handleDownloadReport}>
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </Button>
        </div>
      </header>

      <div className="container mx-auto px-4 py-6 max-w-6xl">
        <Tabs defaultValue="overview" className="space-y-6">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="vitals">Vitals Trends</TabsTrigger>
            <TabsTrigger value="symptoms">Symptoms Log</TabsTrigger>
            <TabsTrigger value="ai-insights">AI Insights</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            {/* Report Summary */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="h-5 w-5" />
                  Health Summary - {report.period}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="text-center p-4 bg-muted rounded-lg">
                    <div className="text-2xl font-bold">{report.summary.totalReadings}</div>
                    <div className="text-sm text-muted-foreground">Total Readings</div>
                  </div>
                  <div className="text-center p-4 bg-muted rounded-lg">
                    <div className="text-2xl font-bold">{report.summary.avgHeartRate}</div>
                    <div className="text-sm text-muted-foreground">Avg Heart Rate</div>
                  </div>
                  <div className="text-center p-4 bg-muted rounded-lg">
                    <div className="text-2xl font-bold">{report.summary.avgBloodPressure}</div>
                    <div className="text-sm text-muted-foreground">Avg Blood Pressure</div>
                  </div>
                  <div className="text-center p-4 bg-muted rounded-lg">
                    <div className="text-2xl font-bold">{report.summary.symptomsReported}</div>
                    <div className="text-sm text-muted-foreground">Symptoms Reported</div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Risk Assessment */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5" />
                  AI Risk Assessment
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {Object.entries(report.riskAssessment).map(([disease, data]) => (
                    <div key={disease} className="p-4 border rounded-lg">
                      <div className="flex justify-between items-center mb-2">
                        <h3 className="font-semibold capitalize">{disease.replace(/([A-Z])/g, ' $1').trim()}</h3>
                        <Badge variant={data.risk <= 30 ? "success" : data.risk <= 60 ? "warning" : "destructive"}>
                          {data.risk}%
                        </Badge>
                      </div>
                      <div className="text-sm text-muted-foreground">
                        Trend: {data.trend}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Recommendations */}
            <Card>
              <CardHeader>
                <CardTitle>AI Recommendations</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {report.recommendations.map((recommendation, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="font-semibold text-primary">{index + 1}.</span>
                      <span className="text-sm">{recommendation}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="vitals" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5" />
                  Vitals Trends
                </CardTitle>
              </CardHeader>
              <CardContent>
                {healthData.length > 0 ? (
                  <HealthChart data={healthData.slice(-7)} />
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    No vitals data available. Start logging your health data to see trends.
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="symptoms" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Symptoms History</CardTitle>
              </CardHeader>
              <CardContent>
                {symptomsData.length > 0 ? (
                  <div className="space-y-4">
                    {symptomsData.map((entry, index) => (
                      <div key={index} className="border rounded-lg p-4">
                        <div className="flex justify-between items-center mb-2">
                          <span className="font-semibold">Entry #{symptomsData.length - index}</span>
                          <span className="text-sm text-muted-foreground">{entry.date}</span>
                        </div>
                        <div className="space-y-2">
                          <div>
                            <span className="text-sm font-medium">Symptoms: </span>
                            <span className="text-sm">
                              {entry.symptoms.map((s: any) => `${s.label} (${s.severity})`).join(', ')}
                            </span>
                          </div>
                          {entry.additionalNotes && (
                            <div>
                              <span className="text-sm font-medium">Notes: </span>
                              <span className="text-sm">{entry.additionalNotes}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    No symptoms logged yet. Use the symptoms tracker to record any health concerns.
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="ai-insights" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>AI-Powered Health Insights</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="p-4 bg-muted rounded-lg">
                  <h3 className="font-semibold mb-2">Pattern Analysis</h3>
                  <p className="text-sm text-muted-foreground">
                    Based on your recent data, your heart rate shows good stability with an average of 72 bpm. 
                    Blood pressure readings are within normal range, indicating good cardiovascular health.
                  </p>
                </div>
                
                <div className="p-4 bg-muted rounded-lg">
                  <h3 className="font-semibold mb-2">Risk Factors Identified</h3>
                  <p className="text-sm text-muted-foreground">
                    Elevated heart disease risk (40%) may be related to age and family history. 
                    Consider lifestyle modifications and regular cardiology consultation.
                  </p>
                </div>
                
                <div className="p-4 bg-muted rounded-lg">
                  <h3 className="font-semibold mb-2">Preventive Measures</h3>
                  <p className="text-sm text-muted-foreground">
                    Continue current medication adherence. Increase physical activity gradually. 
                    Monitor blood pressure daily and maintain a heart-healthy diet.
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default Reports;